version: '3.7'

services:
  sistem-rumah-sakit:
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - ./app/app/.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    ports:
      - 5434:5432
    volumes:
      - sistem_rumah_sakit_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adam1234
      - POSTGRES_DB=sistem_rumah_sakit_db

volumes:
  sistem_rumah_sakit_volume: