"""add antrian table

Revision ID: ce6d3398f894
Revises: 9bfd0d733e71
Create Date: 2021-04-08 14:38:53.129965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6d3398f894'
down_revision = '9bfd0d733e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
