"""add all table

Revision ID: f4b9e560530c
Revises: 
Create Date: 2021-04-02 11:42:04.396048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b9e560530c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pasien',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nama', sa.String(length=30), nullable=False),
    sa.Column('alamat', sa.String(length=130), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=30), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('no_hp', sa.String(length=15), nullable=True),
    sa.Column('bpjs', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pasien_id'), 'pasien', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('dokter',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('nama', sa.String(length=60), nullable=False),
    sa.Column('alamat', sa.String(length=130), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=20), nullable=True),
    sa.Column('tanggal_lahir', sa.DateTime(timezone=True), nullable=True),
    sa.Column('no_hp', sa.String(length=15), nullable=True),
    sa.Column('poli', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dokter_id'), 'dokter', ['id'], unique=False)
    op.create_table('rekam_medis',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dokter_id', sa.BigInteger(), nullable=True),
    sa.Column('pasien_id', sa.BigInteger(), nullable=True),
    sa.Column('keluhan', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dokter_id'], ['dokter.id'], ),
    sa.ForeignKeyConstraint(['pasien_id'], ['pasien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rekam_medis_id'), 'rekam_medis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rekam_medis_id'), table_name='rekam_medis')
    op.drop_table('rekam_medis')
    op.drop_index(op.f('ix_dokter_id'), table_name='dokter')
    op.drop_table('dokter')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pasien_id'), table_name='pasien')
    op.drop_table('pasien')
    # ### end Alembic commands ###
